### ISSUE TITLE
Coordination

### ISSUE THREAD

**Issue by rharkor** [anolilab/multi-semantic-release#13]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/anolilab/multi-semantic-release/blob/main/.github/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/anolilab/multi-semantic-release/blob/main/.github/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/anolilab/multi-semantic-release/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a multi-semantic-release issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anolilab/multi-semantic-release/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] I am willing to provide a PR.

### Describe the bug

Hi, 

In my monorepos I have two sub package and I want them to be coodinated on their versionning, unfortunately this is not the case see the example below:
![image](https://github.com/dhoulb/multi-semantic-release/assets/70844594/cb0d69e1-087d-4c5f-97ca-042289f8edb0)

Also why it always make a new release like 1.1.0-rec.17 => 1.1.0-rec.18 instead of changing the semver version ?

Can anyone help me with this ?

Thank you

### Environment Info

```shell
System:
    OS: Linux 6.2 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (8) x64 Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz
    Memory: 51.67 GB / 62.57 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.0 - /workspaces/rl-idle/node_modules/.bin/npm
    pnpm: 8.8.0 - /usr/local/share/npm-global/bin/pnpm
    bun: 1.0.7 - ~/.bun/bin/bun
  Monorepos:
    Yarn Workspaces: 1.22.19
  npmPackages:
    @semantic-release/changelog: ^6.0.3 => 6.0.3 
    @semantic-release/commit-analyzer: ^11.0.0 => 11.0.0 
    @semantic-release/git: ^10.0.1 => 10.0.1 
    @semantic-release/github: ^9.0.4 => 9.2.1 
    @semantic-release/npm: ^11.0.0 => 11.0.1 
    @semantic-release/release-notes-generator: ^12.0.0 => 12.0.1 
    semantic-release: ^22.0.5 => 22.0.7
```

### Which module system do you use?

- [ ] CJS
- [X] ESM

### Used Package Manager

npm

**Comment by prisis** [comment]
Could you post you repo, semantic-config file and your pipeline?

**Comment by rharkor** [comment]
Yes there is it: https://github.com/rl-IDLE/rl-idle

**Comment by prisis** [comment]
Im sorry, but i cant find any branch or code that use @anolilab/multi-semantic-release
